POST http://127.0.0.1:5000/order/add
Content-Type: application/json

{
    "createDate" : "2023-02-10",
    "customerId" : 1
}


###

POST http://127.0.0.1:5000/payment/add
Content-Type: application/json

{
    "amount" : 15000,
    "payment_mode": "Chek",
    "orderId" : 1
}

###

POST http://127.0.0.1:5000/customer/add
Content-Type: application/json

{
    "name" : "BOUANGA-NIAMBI",
    "deliveryAddress" : "elsirema3@gmail.com",
    "contact" : "+228 70249511",
    "active" : true
}

###

POST http://127.0.0.1:5000/orderDetail/add
Content-Type: application/json

{
    "qty": 2,
    "taxStatus": "Validé",
    "orderId" : 1,
    "itemId": 1
}

###

POST http://127.0.0.1:5000/item/add
Content-Type: application/json

{
    "weight": 6,
    "description": "ventilateur",
    "price": 12000
}


###
POST http://127.0.0.1:5000/orderStatus/add
Content-Type: application/json

{
    "CREATE": 5,
    "SHIPPING": 10,
    "DELIVERED": 12,
    "PAID": 4
}

###
POST http://127.0.0.1:5000/credit/add
Content-Type: application/json

{
    "number": 3,
    "types": "Chaque mois",
    "expideDate": "2023-02-11"
}

###
POST http://127.0.0.1:5000/Cash/add
Content-Type: application/json

{
    "cashTendered": 15.0
}

###
POST http://127.0.0.1:5000/check/add
Content-Type: application/json

{
    "name": "Elsi",
    "bankId": 1
}

###
POST http://127.0.0.1:5000/wiretransfer/add
Content-Type: application/json

{
    "bankId": 1,
    "bankName": "Bank of Africa"
}

###

GET http://127.0.0.1:5000/order

###

GET http://127.0.0.1:5000/customer

###

GET http://127.0.0.1:5000/item


###
GET http://127.0.0.1:5000/payment